# Generated by Django 6.0.3 on 2026-09-01 15:42

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_presentacionproducto_atributos_and_more'),
        ('tenancy', '0004_registra_dominios_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.SlugField(max_length=40)),
                ('tipo', models.CharField(choices=[('TIENDA', 'Punto de venta'), ('BODEGA', 'Bodega'), ('VEHICULO', 'Vehículo de reparto')], default='TIENDA', max_length=20)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'inventory_ubicacion',
                'ordering': ['-es_predeterminada', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste por conteo'), ('TRASLADO', 'Traslado entre ubicaciones'), ('RESERVA', 'Reserva'), ('LIBERACION', 'Liberación de reserva')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('saldo_resultante', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('origen_tipo', models.CharField(blank=True, max_length=60)),
                ('origen_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='catalog.presentacionproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalog.producto')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.ubicacion')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'db_table': 'inventory_movimiento',
                'ordering': ['-fecha', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reservada', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='catalog.producto')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventory.ubicacion')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'db_table': 'inventory_existencia',
                'ordering': ['producto__nombre_producto'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['tenant', 'activa'], name='inventory_ubic_activa_idx'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('tenant', 'codigo'), name='inventory_codigo_ubicacion_unico_por_negocio'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(condition=models.Q(('es_predeterminada', True)), fields=('tenant',), name='inventory_una_sola_ubicacion_predeterminada'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tenant', 'producto', '-fecha'], name='inventory_mov_producto_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tenant', 'origen_tipo', 'origen_id'], name='inventory_mov_origen_idx'),
        ),
        migrations.AddIndex(
            model_name='existencia',
            index=models.Index(fields=['tenant', 'ubicacion'], name='inventory_exis_ubicacion_idx'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.UniqueConstraint(fields=('tenant', 'producto', 'ubicacion'), name='inventory_una_existencia_por_producto_y_ubicacion'),
        ),
    ]
