# Generated by Django 6.0.3 on 2026-09-02 00:48

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_row_level_security'),
        ('orders', '0007_detallepedido_nombre_congelado'),
        ('pos', '0002_row_level_security'),
        ('tenancy', '0004_registra_dominios_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40)),
                ('nombre', models.CharField(max_length=80)),
                ('zona', models.CharField(blank=True, max_length=60)),
                ('capacidad', models.PositiveSmallIntegerField(default=0)),
                ('reservas_simultaneas', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='inventory.ubicacion')),
            ],
            options={
                'verbose_name': 'Recurso reservable',
                'verbose_name_plural': 'Recursos reservables',
                'db_table': 'reservations_recurso',
                'ordering': ['orden', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=120)),
                ('telefono_contacto', models.CharField(blank=True, max_length=40)),
                ('personas', models.PositiveSmallIntegerField(default=1)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmar'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En curso'), ('CUMPLIDA', 'Cumplida'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PENDIENTE', max_length=20)),
                ('origen', models.CharField(choices=[('PANEL', 'Panel del negocio'), ('CAJA', 'Mostrador'), ('TIENDA', 'Tienda online')], default='PANEL', max_length=20)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='orders.cliente')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservations.recurso')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='pos.venta')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservations_reserva',
                'ordering': ['inicio', 'id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recurso', models.CharField(default='Mesa', max_length=40)),
                ('nombre_recurso_plural', models.CharField(default='Mesas', max_length=40)),
                ('duracion_minutos', models.PositiveIntegerField(default=90)),
                ('antelacion_maxima_dias', models.PositiveIntegerField(default=60)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Configuración de reservas',
                'verbose_name_plural': 'Configuración de reservas',
                'db_table': 'reservations_configuracion',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='reservations_una_config_por_negocio')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='recurso',
            constraint=models.UniqueConstraint(fields=('tenant', 'codigo'), name='reservations_recurso_unico'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['tenant', 'inicio'], name='reservations_agenda_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['tenant', 'recurso', 'inicio'], name='reservations_recurso_idx'),
        ),
    ]
