# Generated by Django 6.0.3 on 2026-07-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PEDIDO_NUEVO", "Nuevo pedido"),
                            ("CLIENTE_NUEVO", "Nuevo cliente"),
                            ("SISTEMA", "Sistema / plataforma"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField(blank=True)),
                ("enlace", models.CharField(blank=True, max_length=255)),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notifications_notificacion",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
