# Generated by Django 6.0.3 on 2026-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PEDIDO_NUEVO", "Nuevo pedido"),
                    ("CLIENTE_NUEVO", "Nuevo cliente"),
                    ("PRODUCTO_PERSONALIZADO", "Producto personalizado"),
                    ("SISTEMA", "Sistema / plataforma"),
                ],
                max_length=30,
            ),
        ),
    ]
