# Generated by Django 6.0.3 on 2026-03-25 22:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono_cliente', models.CharField(max_length=25)),
                ('direccion_cliente', models.TextField()),
                ('fecha_registro_cliente', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre_cliente'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=100, unique=True)),
                ('abreviatura_unidad', models.CharField(max_length=10)),
                ('estado_unidad', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nombre_unidad'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_usuario', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('email_usuario', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('rol_usuario', models.CharField(choices=[('ADMIN', 'Administrador de Sede'), ('ANALISTA', 'Analista de Inventario/Pedidos'), ('GERENTE', 'Gerente General')], default='ANALISTA', max_length=20, verbose_name='Rol en el Sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cuenta Activa')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al Staff')),
                ('intentos_fallidos', models.PositiveIntegerField(default=0)),
                ('ultima_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('token_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('token_expiracion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('ultimo_login_exitoso', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_custom_set', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_custom_permissions_set', to='auth.permission', verbose_name='permisos de usuario')),
            ],
            options={
                'verbose_name': 'Usuario de Sistema',
                'verbose_name_plural': 'Usuarios del Fruver',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=150, unique=True)),
                ('estado_categoria', models.BooleanField(default=True)),
                ('abreviatura', models.CharField(max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre_categoria'],
                'indexes': [models.Index(fields=['nombre_categoria'], name='ui_categori_nombre__7990dc_idx'), models.Index(fields=['orden'], name='ui_categori_orden_0284c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EDITADO', 'Editado'), ('CERRADO', 'Cerrado'), ('ENTREGADO', 'Entregado'), ('IMPRESO', 'Impreso')], default='PENDIENTE', max_length=20)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ui.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50, unique=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('estado_producto', models.BooleanField(default=True)),
                ('permite_fraccion', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo_cantidad', models.CharField(choices=[('entero', 'Entero'), ('medio', 'Medio'), ('cuarto', 'Cuartos')], default='entero', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='ui.categoria')),
                ('unidad_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_base', to='ui.unidadmedida')),
            ],
            options={
                'ordering': ['orden', 'nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_presentacion', models.CharField(max_length=200)),
                ('factor_conversion', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado_presentacion', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='ui.producto')),
                ('unidad_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones_venta', to='ui.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, help_text='Precio de la presentación al momento de crear el pedido', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ui.pedido')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ui.presentacionproducto', verbose_name='Producto y Presentación')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'indexes': [models.Index(fields=['pedido'], name='ui_detallep_pedido__ed81c8_idx')],
                'unique_together': {('pedido', 'presentacion')},
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre_producto'], name='ui_producto_nombre__9e7155_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_producto'], name='ui_producto_codigo__2a0c49_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['orden'], name='ui_producto_orden_0c05b9_idx'),
        ),
        migrations.AddIndex(
            model_name='presentacionproducto',
            index=models.Index(fields=['producto'], name='ui_presenta_product_929de7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presentacionproducto',
            unique_together={('producto', 'nombre_presentacion', 'unidad_venta')},
        ),
    ]
