# Generated by Django 6.0.3 on 2026-03-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='precio_unitario_venta',
            new_name='precio_unitario',
        ),
    ]
