# Generated by Django 6.0.3 on 2026-03-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_rename_precio_unitario_venta_detallepedido_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='orden',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
