# Generated by Django 6.0.3 on 2026-04-17 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_alter_producto_codigo_producto_alter_producto_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
