# Generated by Django 6.0.3 on 2026-04-19 18:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_alter_cliente_nombre_cliente_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_personalizado',
            field=models.CharField(blank=True, help_text='Usado cuando el producto no está en el catálogo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio al momento de la venta', max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ui.presentacionproducto', verbose_name='Producto y Presentación'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
    ]
