# Generated by Django 6.0.3 on 2026-04-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_alter_detallepedido_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacionproducto',
            name='unidad_manual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
