# Generated by Django 6.0.3 on 2026-05-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_presentacionproducto_unidad_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
