# Generated by Django 6.0.3 on 2026-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_detallepedido_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='fue_modificado',
            field=models.BooleanField(default=False),
        ),
    ]
