# Generated by Django 6.0.3 on 2026-05-23 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecio',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='ui.presentacionproducto'),
        ),
        migrations.AlterField(
            model_name='historialprecio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presentacionproducto',
            name='unidad_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones_venta', to='ui.unidadmedida'),
        ),
    ]
