# Generated by Django 6.0.3 on 2026-05-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_alter_historialprecio_presentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
