# Generated by Django 6.0.3 on 2026-05-24 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0016_pedido_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_editados', to=settings.AUTH_USER_MODEL),
        ),
    ]
