# Generated by Django 6.0.3 on 2026-06-14 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0017_pedido_editado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('archivo', models.FileField(upload_to='biblioteca/%Y/%m')),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='biblioteca/thumbs')),
                ('tipo', models.CharField(choices=[('IMG', 'Imagen'), ('MP4', 'Video'), ('PDF', 'PDF'), ('DOCX', 'Word')], max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerPublicitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_banner', models.CharField(max_length=200)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ui.bibliotecamultimedia')),
            ],
        ),
        migrations.AddField(
            model_name='bibliotecamultimedia',
            name='categoriaMultimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='ui.categoriamultimedia'),
        ),
        migrations.CreateModel(
            name='DetallePedidoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle_adicional', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONVERTIDO', 'Convertido a catálogo'), ('DESCARTADO', 'Descartado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_manual', to='ui.pedido')),
                ('producto_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_convertidos', to='ui.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.bibliotecamultimedia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='ui.producto')),
            ],
        ),
    ]
