# Generated by Django 6.0.3 on 2026-06-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0019_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='unidad_personalizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ui.unidadmedida'),
        ),
    ]
