# Generated by Django 6.0.3 on 2026-06-21 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0020_detallepedido_unidad_personalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='categoria_manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.categoria'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='es_catalogo',
            field=models.BooleanField(default=False),
        ),
    ]
