# Generated by Django 6.0.3 on 2026-08-28 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(help_text='Identificador en la URL: <slug>.plataforma.com', max_length=63, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('PRUEBA', 'En prueba'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('ARCHIVADO', 'Archivado')], default='PRUEBA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'db_table': 'tenancy_tenant',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('OWNER', 'Dueño'), ('ADMIN', 'Administrador'), ('MANAGER', 'Gerente'), ('SALES', 'Ventas'), ('STAFF', 'Personal')], default='STAFF', max_length=20)),
                ('permisos', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Pertenencia',
                'verbose_name_plural': 'Pertenencias',
                'db_table': 'tenancy_membership',
                'ordering': ['tenant__nombre', 'usuario__nombre_usuario'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'tenant'), name='tenancy_una_pertenencia_por_negocio')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('es_primario', models.BooleanField(default=False)),
                ('verificado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
                'db_table': 'tenancy_domain',
                'ordering': ['-es_primario', 'hostname'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_primario', True)), fields=('tenant',), name='tenancy_un_solo_dominio_primario_por_tenant')],
            },
        ),
    ]
