# Generated by Django 6.0.3 on 2026-08-31 23:02

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_registra_dominios_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='La llave del registro de React.', max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(choices=[('ESTRUCTURA', 'Estructura'), ('CONTENIDO', 'Contenido'), ('CATALOGO', 'Catálogo'), ('PRUEBA_SOCIAL', 'Prueba social'), ('CONVERSION', 'Conversión')], default='CONTENIDO', max_length=20)),
                ('icono', models.CharField(blank=True, max_length=40)),
                ('esquema_props', models.JSONField(blank=True, default=dict, help_text='JSON Schema de las propiedades que acepta.')),
                ('variantes', models.JSONField(blank=True, default=list, help_text='Aspectos disponibles: [{"codigo": "rejilla-4", "nombre": "Rejilla"}]')),
                ('requiere_datos', models.BooleanField(default=False)),
                ('unico_por_pagina', models.BooleanField(default=False)),
                ('a_sangre', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'db_table': 'storefront_bloque',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('valores', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'storefront_tema',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(help_text='Empieza por /. La home es exactamente «/».', max_length=120)),
                ('titulo', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('HOME', 'Inicio'), ('CATALOGO', 'Catálogo'), ('PRODUCTO', 'Ficha de producto'), ('CATEGORIA', 'Categoría'), ('LIBRE', 'Página libre')], default='LIBRE', max_length=20)),
                ('seo_titulo', models.CharField(blank=True, max_length=160)),
                ('seo_descripcion', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'db_table': 'storefront_pagina',
                'ordering': ['ruta'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, help_text='Alimentos, Moda, Restaurante…', max_length=60)),
                ('vista_previa', models.URLField(blank=True)),
                ('paginas', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='storefront.tema')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'db_table': 'storefront_plantilla',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VersionPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('ARCHIVADA', 'Archivada')], default='BORRADOR', max_length=20)),
                ('composicion', models.JSONField(blank=True, default=list)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_de_pagina', to=settings.AUTH_USER_MODEL)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='storefront.pagina')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Versión de página',
                'verbose_name_plural': 'Versiones de página',
                'db_table': 'storefront_versionpagina',
                'ordering': ['-numero'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='pagina',
            constraint=models.UniqueConstraint(fields=('tenant', 'ruta'), name='storefront_una_ruta_por_negocio'),
        ),
        migrations.AddConstraint(
            model_name='plantilla',
            constraint=models.UniqueConstraint(condition=models.Q(('es_predeterminada', True)), fields=('es_predeterminada',), name='storefront_una_sola_plantilla_por_defecto'),
        ),
        migrations.AddConstraint(
            model_name='versionpagina',
            constraint=models.UniqueConstraint(fields=('pagina', 'numero'), name='storefront_un_numero_por_pagina'),
        ),
        migrations.AddConstraint(
            model_name='versionpagina',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PUBLICADA')), fields=('pagina',), name='storefront_una_sola_publicada'),
        ),
        migrations.AddConstraint(
            model_name='versionpagina',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'BORRADOR')), fields=('pagina',), name='storefront_un_solo_borrador'),
        ),
    ]
