# Generated by Django 6.0.3 on 2026-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_esquemas_y_variantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('grupo', models.CharField(choices=[('MARCA', 'Marca'), ('NAVEGACION', 'Navegación'), ('TIPOGRAFIA', 'Tipografía'), ('SUPERFICIE', 'Superficies'), ('FORMA', 'Formas y espacios')], default='MARCA', max_length=20)),
                ('tipo', models.CharField(choices=[('COLOR', 'Color'), ('MEDIDA', 'Medida'), ('NUMERO', 'Número'), ('OPCION', 'Opción'), ('TEXTO', 'Texto')], default='COLOR', max_length=20)),
                ('variable_css', models.CharField(help_text='La variable que la tienda lee: --navbar-fondo.', max_length=60)),
                ('valor_por_defecto', models.CharField(blank=True, max_length=120)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('unidad', models.CharField(blank=True, max_length=8)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Token de tema',
                'verbose_name_plural': 'Tokens de tema',
                'db_table': 'storefront_tokentema',
                'ordering': ['grupo', 'orden', 'nombre'],
            },
        ),
    ]
