# Generated by Django 6.0.3 on 2026-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_siembra_tokens_de_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='tema_valores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
