# Generated by Django 6.0.3 on 2026-09-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_portada_y_plantilla_cosecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='tipo',
            field=models.CharField(choices=[('HOME', 'Inicio'), ('CATALOGO', 'Catálogo'), ('PRODUCTO', 'Ficha de producto'), ('CATEGORIA', 'Categoría'), ('LIBRE', 'Página libre'), ('LAYOUT', 'Cabecera y pie')], default='LIBRE', max_length=20),
        ),
    ]
