# Generated by Django 6.0.3 on 2026-09-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0011_estilo_de_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentema',
            name='grupo',
            field=models.CharField(choices=[('MARCA', 'Marca'), ('NAVEGACION', 'Navegación'), ('TIPOGRAFIA', 'Tipografía'), ('SUPERFICIE', 'Superficies'), ('FORMA', 'Formas y espacios'), ('DENSIDAD', 'Densidad')], default='MARCA', max_length=20),
        ),
    ]
