# Generated by Django 6.0.3 on 2026-09-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0013_tokens_de_densidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='marca',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
