# Generated by Django 6.0.3 on 2026-09-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0019_belleza_autentica'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='tokens_admitidos',
            field=models.JSONField(blank=True, default=list, help_text='Códigos de TokenTema que este bloque puede sobrescribir.'),
        ),
        migrations.AlterField(
            model_name='tokentema',
            name='grupo',
            field=models.CharField(choices=[('MARCA', 'Marca'), ('NAVEGACION', 'Navegación'), ('TIPOGRAFIA', 'Tipografía'), ('SUPERFICIE', 'Superficies'), ('FORMA', 'Formas y espacios'), ('ESPACIADO', 'Espaciado'), ('SOMBRA', 'Sombras'), ('DENSIDAD', 'Densidad'), ('CAJA', 'Punto de venta')], default='MARCA', max_length=20),
        ),
    ]
