# Generated by Django 6.0.3 on 2026-08-28 15:32

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_tenant_obligatorio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mensajecontacto',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
