# Generated by Django 6.0.3 on 2026-09-06 01:21

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_managers_con_ambito'),
        ('tenancy', '0004_registra_dominios_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('origen', models.CharField(blank=True, default='tienda', max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'db_table': 'contact_suscriptor',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'email'), name='contact_un_correo_por_negocio')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
