# Generated by Django 6.0.3 on 2026-09-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='motivo',
            field=models.CharField(choices=[('PEDIDO', 'Hacer un pedido'), ('COTIZACION', 'Cotización'), ('PRODUCTO_ESPECIAL', 'Producto fuera del catálogo'), ('CONSULTA', 'Consulta')], default='CONSULTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
