# Generated by Django 6.0.3 on 2026-07-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="banners/"),
                ),
                ("etiqueta", models.CharField(blank=True, max_length=100)),
                ("titulo", models.CharField(max_length=200)),
                ("texto", models.TextField(blank=True)),
                ("cta_texto", models.CharField(blank=True, max_length=60)),
                ("cta_href", models.CharField(blank=True, max_length=255)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Banner de inicio",
                "verbose_name_plural": "Banners de inicio",
                "db_table": "content_promobanner",
                "ordering": ["orden", "-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "whatsapp_numero",
                    models.CharField(
                        blank=True,
                        help_text="Formato internacional sin '+', ej: 573001234567",
                        max_length=20,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=25)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=120)),
                ("horario", models.CharField(blank=True, max_length=150)),
                ("historia", models.TextField(blank=True)),
                ("mision", models.TextField(blank=True)),
                ("factura_nit", models.CharField(blank=True, max_length=50)),
                ("factura_proveedor", models.CharField(blank=True, max_length=150)),
                ("factura_telefono", models.CharField(blank=True, max_length=25)),
                ("factura_direccion", models.CharField(blank=True, max_length=255)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del sitio",
                "verbose_name_plural": "Configuración del sitio",
                "db_table": "content_siteconfig",
            },
        ),
        migrations.CreateModel(
            name="Testimonio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("rol", models.CharField(blank=True, max_length=150)),
                ("texto", models.TextField()),
                ("estrellas", models.PositiveSmallIntegerField(default=5)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "content_testimonio",
                "ordering": ["orden", "-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="TrustBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        choices=[
                            ("leaf", "Hoja"),
                            ("truck", "Camión"),
                            ("shield", "Escudo"),
                            ("users", "Usuarios"),
                        ],
                        default="leaf",
                        max_length=20,
                    ),
                ),
                ("valor", models.CharField(max_length=40)),
                ("etiqueta", models.CharField(max_length=150)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sello de confianza",
                "verbose_name_plural": "Sellos de confianza",
                "db_table": "content_trustbadge",
                "ordering": ["orden", "id"],
            },
        ),
    ]
