# Generated by Django 6.0.3 on 2026-07-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="nombre_empresa",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
