# Generated by Django 6.0.3 on 2026-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_siteconfig_nombre_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="color_primario",
            field=models.CharField(blank=True, default="#16a34a", max_length=7),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="whatsapp_mensaje_pedido",
            field=models.TextField(
                blank=True,
                default="Hola, soy {nombre} y quiero confirmar mi pedido #{pedido_id} por un total de {total}.",
                help_text="Placeholders disponibles: {nombre}, {pedido_id}, {total}",
            ),
        ),
    ]
