# Generated by Django 6.0.3 on 2026-07-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_siteconfig_color_primario_siteconfig_facebook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="factura_eslogan",
            field=models.CharField(
                blank=True, default="Distribuidora Mayorista", max_length=150
            ),
        ),
    ]
