# Generated by Django 6.0.3 on 2026-08-09 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_siteconfig_factura_eslogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ancho_buscador',
            field=models.PositiveIntegerField(default=420, validators=[django.core.validators.MinValueValidator(240), django.core.validators.MaxValueValidator(640)]),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_fondo',
            field=models.CharField(blank=True, default='#f6faf7', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_primario_texto',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_secundario',
            field=models.CharField(blank=True, default='#f59e0b', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_secundario_texto',
            field=models.CharField(blank=True, default='#0b1f17', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_superficie',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_texto',
            field=models.CharField(blank=True, default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='espaciado_navbar',
            field=models.PositiveIntegerField(default=0, help_text='Espacio extra (px) entre el logo y las opciones del navbar.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(64)]),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='fuente',
            field=models.CharField(choices=[('poppins', 'Poppins'), ('inter', 'Inter'), ('nunito', 'Nunito'), ('work-sans', 'Work Sans'), ('jakarta', 'Plus Jakarta Sans'), ('quicksand', 'Quicksand')], default='poppins', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='radio_boton',
            field=models.CharField(choices=[('redondeado', 'Redondeado (píldora)'), ('suave', 'Suave'), ('cuadrado', 'Cuadrado')], default='redondeado', max_length=20),
        ),
    ]
