# Generated by Django 6.0.3 on 2026-08-10 02:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('content', '0005_siteconfig_ancho_buscador_siteconfig_color_fondo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(choices=[('truck', 'Camión'), ('clock', 'Reloj'), ('package', 'Paquete'), ('wallet', 'Billetera'), ('headset', 'Auriculares (atención)'), ('check', 'Check'), ('shield', 'Escudo'), ('users', 'Usuarios')], default='check', max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Beneficio comercial',
                'verbose_name_plural': 'Beneficios comerciales',
                'db_table': 'content_beneficiocomercial',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cotizacion_texto',
            field=models.CharField(blank=True, default='Cuéntanos qué necesitas y te confirmamos precio y disponibilidad en minutos.', max_length=220),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cotizacion_titulo',
            field=models.CharField(blank=True, default='¿Pedido grande o fuera de catálogo?', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_final_texto',
            field=models.CharField(blank=True, default='Explora el catálogo completo y arma tu pedido en minutos.', max_length=220),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_final_titulo',
            field=models.CharField(blank=True, default='Tu próximo pedido puede estar en camino hoy mismo', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='paso1_texto',
            field=models.CharField(blank=True, default='Filtra por categoría o busca directo lo que necesitas para tu negocio.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='paso1_titulo',
            field=models.CharField(blank=True, default='Explora el catálogo', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='paso2_texto',
            field=models.CharField(blank=True, default='Elige presentación, unidad y cantidad — hasta fraccionada si el producto lo permite.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='paso2_titulo',
            field=models.CharField(blank=True, default='Arma tu pedido', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='paso3_texto',
            field=models.CharField(blank=True, default='Confirmamos contigo por WhatsApp y despachamos directo a tu negocio.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='paso3_titulo',
            field=models.CharField(blank=True, default='Recibe tu entrega', max_length=80),
        ),
        migrations.AddField(
            model_name='trustbadge',
            name='tipo',
            field=models.CharField(choices=[('insignia', "Insignia (barra de confianza, ej: 'Entrega 24-48h')"), ('estadistica', "Estadística (número grande, ej: '+350 productos')")], default='insignia', max_length=20),
        ),
        migrations.CreateModel(
            name='OfertaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Opcional: si se define, el Home muestra un contador.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='catalog.presentacionproducto')),
            ],
            options={
                'verbose_name': 'Oferta de producto',
                'verbose_name_plural': 'Ofertas de la semana',
                'db_table': 'content_ofertaproducto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
