# Generated by Django 6.0.3 on 2026-08-29 18:45

import apps.tenancy.almacenamiento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_managers_con_ambito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobanner',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_banner),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_identidad),
        ),
    ]
