# Generated by Django 6.0.3 on 2026-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rutas_por_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='tokens',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
