# Generated by Django 6.0.6 on 2026-09-10 23:30

import apps.tenancy.almacenamiento
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_limpieza_datos_prueba_cosecha'),
        ('tenancy', '0004_registra_dominios_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_anuncio)),
                ('etiqueta', models.CharField(blank=True, max_length=60)),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField(blank=True)),
                ('cta_texto', models.CharField(blank=True, max_length=60)),
                ('cta_href', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'db_table': 'content_anuncio',
                'ordering': ['orden', '-fecha_creacion'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
