# Generated by Django 6.0.6 on 2026-09-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_contenedor_mas_ancho_cosecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiocomercial',
            name='icono',
            field=models.CharField(choices=[('truck', 'Camión'), ('clock', 'Reloj'), ('package', 'Paquete'), ('wallet', 'Billetera'), ('headset', 'Auriculares (atención)'), ('check', 'Check'), ('shield', 'Escudo'), ('users', 'Usuarios'), ('basket', 'Canasta')], default='check', max_length=20),
        ),
    ]
