# Generated by Django 6.0.3 on 2026-09-27 17:13

import apps.tenancy.almacenamiento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_preserva_chip_factura_gran_cosecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imagen_movil',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_anuncio),
        ),
        migrations.AddField(
            model_name='beneficiocomercial',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_contenido),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='imagen_movil',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_banner),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_contenido),
        ),
    ]
