# Generated by Django 6.0.3 on 2026-09-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_identificacion_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='identificacion_clientes',
            field=models.CharField(choices=[('nombre', 'Solo nombre'), ('cedula', 'Cédula'), ('cuenta', 'Usuario y contraseña')], db_default='nombre', default='nombre', help_text='Solo nombre: como siempre. Cédula: el cliente se identifica con su cédula, da sus datos una sola vez y puede consultar y repetir sus pedidos.', max_length=10),
        ),
    ]
