# Generated by Django 6.0.3 on 2026-07-21 00:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=200, unique=True)),
                ("telefono_cliente", models.CharField(blank=True, max_length=25)),
                ("direccion_cliente", models.TextField(blank=True)),
                ("fecha_registro_cliente", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ui_cliente",
                "ordering": ["nombre_cliente"],
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_personalizado",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=12,
                    ),
                ),
                ("es_catalogo", models.BooleanField(default=False)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("fue_modificado", models.BooleanField(default=False)),
                (
                    "categoria_manual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.categoria",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "presentacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.presentacionproducto",
                    ),
                ),
                (
                    "unidad_personalizada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.unidadmedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pedido",
                "verbose_name_plural": "Detalles de Pedidos",
                "db_table": "ui_detallepedido",
            },
        ),
        migrations.CreateModel(
            name="HistorialDetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("campo", models.CharField(max_length=100)),
                ("valor_anterior", models.TextField()),
                ("valor_nuevo", models.TextField()),
                ("motivo", models.TextField(blank=True, null=True)),
                (
                    "detalle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="orders.detallepedido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ui_historialdetallepedido",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EDITADO", "Editado"),
                            ("CERRADO", "Cerrado"),
                            ("ENTREGADO", "Entregado"),
                            ("IMPRESO", "Impreso"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "total_pedido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="orders.cliente",
                    ),
                ),
                (
                    "editado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_editados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ui_pedido",
                "ordering": ["fecha_pedido"],
            },
        ),
        migrations.CreateModel(
            name="DetallePedidoManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=300)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unidad", models.CharField(blank=True, max_length=50, null=True)),
                ("detalle_adicional", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONVERTIDO", "Convertido a catálogo"),
                            ("DESCARTADO", "Descartado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "producto_catalogo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos_convertidos",
                        to="catalog.producto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_manual",
                        to="orders.pedido",
                    ),
                ),
            ],
            options={
                "db_table": "ui_detallepedidomanual",
            },
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="orders.pedido",
            ),
        ),
        migrations.AddIndex(
            model_name="detallepedido",
            index=models.Index(
                fields=["pedido"], name="ui_detallep_pedido__ed81c8_idx"
            ),
        ),
    ]
