# Generated by Django 6.0.3 on 2026-07-21 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotePedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMPRESION', 'Impresión'), ('ENTREGA', 'Entrega')], max_length=20)),
                ('cantidad_pedidos', models.PositiveIntegerField(default=0)),
                ('total_lote', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedidos', models.ManyToManyField(related_name='lotes', to='orders.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lotes de Pedidos',
                'db_table': 'ui_lotepedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
