# Generated by Django 6.0.3 on 2026-07-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0002_lotepedidos"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallepedido",
            name="estado_revision",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("ACEPTADO", "Aceptado"),
                    ("RECHAZADO", "Rechazado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="producto_generado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generado_desde_pedido",
                to="catalog.producto",
            ),
        ),
    ]
