# Generated by Django 6.0.3 on 2026-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_managers_con_ambito'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_congelado',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
