# Generated by Django 6.0.3 on 2026-09-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_detallepedido_nombre_congelado'),
        ('tenancy', '0004_registra_dominios_iniciales'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='orders_cliente_unico_por_negocio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='acepto_precios_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento_cliente',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('documento_cliente', ''), _negated=True), fields=('tenant', 'documento_cliente'), name='orders_cliente_documento_unico_por_negocio'),
        ),
    ]
