# Generated by Django 6.0.3 on 2026-09-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cliente_por_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento_cliente',
            field=models.CharField(blank=True, db_default='', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
    ]
