# Generated by Django 6.0.3 on 2026-08-29 19:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_registra_dominios_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(help_text='Agrupa los permisos en el panel: Catálogo, Pedidos…', max_length=60)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('etiqueta', models.CharField(help_text='Lo que lee el dueño del negocio, no el codename.', max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True, help_text='Desactivarlo lo oculta en todos los negocios, sin borrar nada.')),
            ],
            options={
                'verbose_name': 'Permiso disponible',
                'verbose_name_plural': 'Permisos disponibles',
                'db_table': 'billing_permisodisponible',
                'ordering': ['modulo', 'orden', 'etiqueta'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(default='COP', max_length=3)),
                ('permisos', models.JSONField(blank=True, default=list)),
                ('limites', models.JSONField(blank=True, default=dict)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_plan',
                'ordering': ['orden', 'precio_mensual'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_predeterminado', True)), fields=('es_predeterminado',), name='billing_un_solo_plan_por_defecto')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRUEBA', 'En prueba'), ('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PRUEBA', max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacío = sin fecha de término.', null=True)),
                ('limites_extra', models.JSONField(blank=True, default=dict)),
                ('notas', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='billing.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'billing_subscription',
                'ordering': ['tenant__nombre'],
            },
        ),
    ]
