# Generated by Django 6.0.3 on 2026-08-29 20:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


"""
Estructura del motor comercial: productos, caracteristicas, tipos de limite y
precios con vigencia.

Solo anade. Las columnas viejas de `Plan` (`activo`, `moneda`,
`precio_mensual`) siguen aqui a proposito: la 0004 necesita leerlas para
convertirlas en filas de `PrecioPlan` y en un estado, y la 0005 las retira
cuando ya no queda nada dentro. Borrarlas en el mismo paso que se crean las
tablas nuevas habria tirado los precios de los planes existentes.
"""


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_siembra_catalogo_y_planes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
                'db_table': 'billing_caracteristica',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(blank=True, help_text='Agrupa productos en el catálogo: Ventas, Operación, Datos…', max_length=60)),
                ('icono', models.CharField(blank=True, max_length=40)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('ARCHIVADO', 'Archivado')], default='ACTIVO', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'billing_producto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='La clave dentro de `Plan.limites`.', max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('unidad', models.CharField(choices=[('UNIDAD', 'Unidades'), ('MB', 'Megabytes'), ('PETICIONES', 'Peticiones')], default='UNIDAD', max_length=20)),
                ('por_periodo', models.BooleanField(default=False, help_text='Marca los que se reinician cada ciclo de facturación.')),
                ('valor_por_defecto', models.IntegerField(blank=True, help_text='Lo que se aplica si un plan no lo fija. Vacío = sin límite.', null=True)),
                ('medido', models.BooleanField(default=False, help_text='Si la plataforma sabe cuánto se está consumiendo.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de límite',
                'verbose_name_plural': 'Tipos de límite',
                'db_table': 'billing_tipolimite',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='plan',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('ARCHIVADO', 'Archivado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='origen',
            field=models.ForeignKey(blank=True, help_text='La versión anterior de la que salió este plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_dias',
            field=models.PositiveIntegerField(default=0, help_text='0 desactiva la prueba gratuita en este plan.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='fecha_fin_prueba',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='importe_pactado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='subscription',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='periodicidad',
            field=models.CharField(choices=[('UNICO', 'Pago único'), ('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='permisodisponible',
            name='modulo',
            field=models.CharField(help_text='Etiqueta del producto; se sincroniza con él.', max_length=60),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='estado',
            field=models.CharField(choices=[('PRUEBA', 'En prueba'), ('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PRUEBA', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, related_name='planes', to='billing.caracteristica'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caracteristicas', to='billing.producto'),
        ),
        migrations.AddField(
            model_name='permisodisponible',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='A qué solución de Crynex pertenece este permiso.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='billing.producto'),
        ),
        migrations.CreateModel(
            name='PrecioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='COP', max_length=3)),
                ('periodicidad', models.CharField(choices=[('UNICO', 'Pago único'), ('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, help_text='Vacío = sigue vigente.', null=True)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='billing.plan')),
            ],
            options={
                'verbose_name': 'Precio de plan',
                'verbose_name_plural': 'Precios de plan',
                'db_table': 'billing_precioplan',
                'ordering': ['plan', 'moneda', 'periodicidad', '-vigente_desde'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'moneda', 'periodicidad', 'vigente_desde'), name='billing_un_precio_por_combinacion_y_fecha')],
            },
        ),
    ]
