# Generated by Django 6.0.3 on 2026-07-21 00:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PresentacionProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_presentacion", models.CharField(max_length=200)),
                (
                    "factor_conversion",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0001)],
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unidad_manual",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("estado_presentacion", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ui_presentacionproducto",
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_unidad", models.CharField(max_length=100, unique=True)),
                ("abreviatura_unidad", models.CharField(max_length=10)),
                ("estado_unidad", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "ui_unidadmedida",
                "ordering": ["nombre_unidad"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_categoria", models.CharField(max_length=150, unique=True)),
                ("estado_categoria", models.BooleanField(default=True)),
                ("abreviatura", models.CharField(max_length=50)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categorías",
                "db_table": "ui_categoria",
                "ordering": ["orden", "nombre_categoria"],
                "indexes": [
                    models.Index(
                        fields=["nombre_categoria"],
                        name="ui_categori_nombre__7990dc_idx",
                    ),
                    models.Index(fields=["orden"], name="ui_categori_orden_0284c3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistorialPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_anterior",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("precio_nuevo", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "presentacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_precios",
                        to="catalog.presentacionproducto",
                    ),
                ),
            ],
            options={
                "db_table": "ui_historialprecio",
                "ordering": ["-fecha_cambio"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_producto",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("nombre_producto", models.CharField(max_length=200)),
                ("estado_producto", models.BooleanField(default=True)),
                ("permite_fraccion", models.BooleanField(default=False)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("orden", models.PositiveIntegerField(editable=False)),
                (
                    "tipo_cantidad",
                    models.CharField(
                        choices=[
                            ("entero", "Entero"),
                            ("medio", "Medio"),
                            ("cuarto", "Cuartos"),
                        ],
                        default="entero",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="catalog.categoria",
                    ),
                ),
                (
                    "unidad_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos_base",
                        to="catalog.unidadmedida",
                    ),
                ),
            ],
            options={
                "db_table": "ui_producto",
                "ordering": ["orden", "nombre_producto"],
            },
        ),
        migrations.AddField(
            model_name="presentacionproducto",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentaciones",
                to="catalog.producto",
            ),
        ),
        migrations.AddField(
            model_name="presentacionproducto",
            name="unidad_venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentaciones_venta",
                to="catalog.unidadmedida",
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["nombre_producto"], name="ui_producto_nombre__9e7155_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["codigo_producto"], name="ui_producto_codigo__2a0c49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["orden"], name="ui_producto_orden_0c05b9_idx"),
        ),
        migrations.AddIndex(
            model_name="presentacionproducto",
            index=models.Index(
                fields=["producto"], name="ui_presenta_product_929de7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="presentacionproducto",
            unique_together={("producto", "nombre_presentacion", "unidad_venta")},
        ),
    ]
