# Generated by Django 6.0.3 on 2026-08-29 18:45

import apps.tenancy.almacenamiento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_managers_con_ambito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_categoria),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_producto),
        ),
    ]
