# Generated by Django 6.0.3 on 2026-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rutas_por_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacionproducto',
            name='atributos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='producto',
            name='controla_stock',
            field=models.BooleanField(default=False),
        ),
    ]
