# Generated by Django 6.0.3 on 2026-09-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_presentacionproducto_atributos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cta_texto',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='categoria',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
