# Generated by Django 6.0.3 on 2026-09-27 16:18

import apps.tenancy.almacenamiento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_imagen_mango_gran_cosecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacionproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenancy.almacenamiento.ruta_presentacion),
        ),
    ]
