# Generated by Django 6.0.3 on 2026-07-21 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "nombre_usuario",
                    models.CharField(max_length=150, verbose_name="Nombre Completo"),
                ),
                (
                    "email_usuario",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "rol_usuario",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador de Sede"),
                            ("ANALISTA", "Analista de Inventario/Pedidos"),
                            ("GERENTE", "Gerente General"),
                        ],
                        default="ANALISTA",
                        max_length=20,
                        verbose_name="Rol en el Sistema",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Cuenta Activa"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Acceso al Staff"),
                ),
                ("intentos_fallidos", models.PositiveIntegerField(default=0)),
                ("ultima_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("bloqueado_hasta", models.DateTimeField(blank=True, null=True)),
                (
                    "token_verificacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("token_expiracion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("ultima_modificacion", models.DateTimeField(auto_now=True)),
                ("ultimo_login_exitoso", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="usuario_custom_set",
                        to="auth.group",
                        verbose_name="grupos",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="usuario_custom_permissions_set",
                        to="auth.permission",
                        verbose_name="permisos de usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario de Sistema",
                "verbose_name_plural": "Usuarios del Fruver",
                "db_table": "ui_usuario",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
