# Generated by Django 6.0.3 on 2026-07-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="sidebar_layout",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
