# Generated by Django 6.0.3 on 2026-07-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_usuario_sidebar_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="notificaciones_silenciadas",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
