# Generated by Django 6.0.3 on 2026-07-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_usuario_notificaciones_silenciadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="debe_cambiar_password",
            field=models.BooleanField(
                default=False, verbose_name="Debe cambiar contraseña"
            ),
        ),
    ]
