# Generated by Django 6.0.3 on 2026-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_staff_plataforma',
            field=models.BooleanField(default=False, help_text='Acceso al panel de la plataforma: planes, permisos y negocios.', verbose_name='Administra Crynex'),
        ),
    ]
