# Generated by Django 6.0.3 on 2026-07-25 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="biblioteca/%Y/%m/")),
                ("nombre_original", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("IMAGEN", "Imagen"),
                            ("VIDEO", "Video"),
                            ("DOCUMENTO", "Documento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("tamano", models.PositiveIntegerField(help_text="Tamaño en bytes")),
                ("ancho", models.PositiveIntegerField(blank=True, null=True)),
                ("alto", models.PositiveIntegerField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo",
                "verbose_name_plural": "Archivos",
                "db_table": "media_archivo",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(fields=["tipo"], name="media_archi_tipo_503871_idx")
                ],
            },
        ),
    ]
