# Generated by Django 6.0.3 on 2026-08-29 18:45

import apps.tenancy.almacenamiento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_managers_con_ambito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=apps.tenancy.almacenamiento.ruta_biblioteca),
        ),
    ]
