# Generated by Django 6.0.3 on 2026-09-01 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0006_producto_inventario'),
        ('storefront', '0006_aspecto_de_plantilla'),
        ('tenancy', '0004_registra_dominios_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=60)),
                ('icono', models.CharField(blank=True, max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('modulos', models.JSONField(blank=True, default=list)),
                ('capacidades', models.JSONField(blank=True, default=dict)),
                ('esquema_atributos', models.JSONField(blank=True, default=list)),
                ('perfil_pos', models.JSONField(blank=True, default=dict)),
                ('politica_stock', models.JSONField(blank=True, default=dict)),
                ('dashboard', models.JSONField(blank=True, default=list)),
                ('senales', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='storefront.plantilla')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='storefront.tema')),
            ],
            options={
                'verbose_name': 'Preset de negocio',
                'verbose_name_plural': 'Presets de negocio',
                'db_table': 'business_preset',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_version_origen', models.PositiveIntegerField(default=0)),
                ('sector', models.CharField(blank=True, max_length=60)),
                ('capacidades', models.JSONField(blank=True, default=dict)),
                ('esquema_atributos', models.JSONField(blank=True, default=list)),
                ('perfil_pos', models.JSONField(blank=True, default=dict)),
                ('politica_stock', models.JSONField(blank=True, default=dict)),
                ('dashboard', models.JSONField(blank=True, default=list)),
                ('respuestas_alta', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='tenancy.tenant')),
                ('preset_origen', models.ForeignKey(blank=True, help_text='De dónde se copió. No es fuente de verdad: solo trazabilidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to='business.preset')),
            ],
            options={
                'verbose_name': 'Perfil de negocio',
                'verbose_name_plural': 'Perfiles de negocio',
                'db_table': 'business_perfilnegocio',
                'ordering': ['tenant__nombre'],
            },
        ),
        migrations.CreateModel(
            name='TenantModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('activado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulos_activados', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activaciones', to='billing.producto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Módulo del negocio',
                'verbose_name_plural': 'Módulos del negocio',
                'db_table': 'business_tenantmodulo',
                'ordering': ['modulo__orden', 'modulo__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='preset',
            constraint=models.UniqueConstraint(condition=models.Q(('es_predeterminado', True)), fields=('es_predeterminado',), name='business_un_solo_preset_por_defecto'),
        ),
        migrations.AddConstraint(
            model_name='tenantmodulo',
            constraint=models.UniqueConstraint(fields=('tenant', 'modulo'), name='business_un_modulo_por_negocio'),
        ),
    ]
